name: sustainability-clustering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=2.0.3
  - numpy>=1.24.3
  - scipy>=1.11.1
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.2
  - seaborn>=0.12.2
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - statsmodels>=0.14.0
  - openpyxl>=3.1.2
  - xlrd>=2.0.1
  - tqdm>=4.65.0
  - networkx>=3.1
  - plotly>=5.15.0
  - pip
  - pip:
    - factor-analyzer>=0.4.1
    - prince>=0.7.1
    - pingouin>=0.5.3
    - fuzzy-c-means>=1.7.0
